/**
 * build-schema.mjs — concatenates every migrations/*.sql (in filename order)
 * and writes src/shared/schema-embed.ts so the Worker can bootstrap a cold D1
 * (no `wrangler d1 migrations apply` step) without FS access at runtime.
 *
 * Single source of truth: the runtime DDL is generated from the migration
 * files, so the embedded SQL and migrations/ never drift. Re-run after adding
 * or editing a migration. Wired into `npm run build:schema` (and `build`) in
 * package.json. Mirrors scripts/build-embed.mjs.
 *
 * Constraint on migrations: every statement must stay idempotent
 * (CREATE … IF NOT EXISTS / INSERT OR IGNORE / DROP … IF EXISTS) because
 * ensureSchema replays the full concatenation on every cold isolate.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const migrationsDir = resolve(root, "migrations");

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

if (files.length === 0) {
  console.error("build-schema: no migrations/*.sql found");
  process.exit(1);
}

const sql = files
  .map((f) => `-- ${f}\n${readFileSync(resolve(migrationsDir, f), "utf8")}`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/build-schema.mjs — do not edit by hand.
// Re-run \`npm run build:schema\` to regenerate from migrations/*.sql.
// Embedded: ${files.join(", ")}
export const SCHEMA_SQL: string = ${JSON.stringify(sql)};
`;

writeFileSync(resolve(root, "src/shared/schema-embed.ts"), out, "utf8");
console.log(`build-schema: wrote src/shared/schema-embed.ts (${files.length} migrations)`);
