/**
 * build-embed.mjs — reads dist/stratus.js and writes src/script/stratus-embed.ts
 * so the Worker can serve the built, minified tracking script without FS access.
 *
 * Run after `npm run build:script`. Included in `npm run build:script` pipeline
 * via `build:embed` script in package.json.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const src = readFileSync(resolve(root, "dist/stratus.js"), "utf8").trim();
// Escape backticks / backslashes for template literal embedding
const escaped = src.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out = `// AUTO-GENERATED by scripts/build-embed.mjs — do not edit by hand.
// Re-run \`npm run build:script\` to regenerate.
export const STRATUS_JS: string = \`${escaped}\`;
`;

// Written to src/shared/ (not src/script/) so the main tsconfig picks it up.
// src/script is excluded from the main tsconfig (DOM types); this file is plain TS.
writeFileSync(resolve(root, "src/shared/stratus-embed.ts"), out, "utf8");
console.log("build-embed: wrote src/shared/stratus-embed.ts");
