/**
 * build-schema.mjs — reads migrations/0001_init.sql and writes
 * src/shared/schema-embed.ts so the Worker can bootstrap a cold D1 (no
 * `wrangler d1 migrations apply` step) without FS access at runtime.
 *
 * Single source of truth: the runtime DDL is generated from the migration file,
 * so the embedded SQL and migrations/ never drift. Re-run after editing the
 * migration. Wired into `npm run build:schema` (and `build`) in package.json.
 * Mirrors scripts/build-embed.mjs.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const sql = readFileSync(resolve(root, "migrations/0001_init.sql"), "utf8");

const out = `// AUTO-GENERATED by scripts/build-schema.mjs — do not edit by hand.
// Re-run \`npm run build:schema\` to regenerate from migrations/0001_init.sql.
export const SCHEMA_SQL: string = ${JSON.stringify(sql)};
`;

writeFileSync(resolve(root, "src/shared/schema-embed.ts"), out, "utf8");
console.log("build-schema: wrote src/shared/schema-embed.ts");
