/**
 * gen-map.mjs — rasterise a world outline into the dashboard's hex dot map.
 *
 * Input: jsVectorMap 1.6.0's `dist/maps/world.js` (MIT). It is no longer
 * vendored; recover it from git history or the npm tarball, e.g.
 *   git show 1f5f677:public/vendor/jsvectormap@1.6.0/world.js > /tmp/world.js
 *   node scripts/gen-map.mjs /tmp/world.js
 *
 * Output (both committed):
 *   public/assets/map-base.svg        — every land dot, one static cacheable file
 *   src/dashboard/render/map-data.ts  — per-ISO-code dot paths, so the SSR can
 *                                       light any country with no client library
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = process.argv[2];
if (!input) {
  console.error("usage: node scripts/gen-map.mjs <path to jsvectormap world.js>");
  process.exit(1);
}

let map;
globalThis.jsVectorMap = {
  addMap: (_name, m) => {
    map = m;
  },
};
new Function(readFileSync(input, "utf8"))();

// Parse each country's SVG path (M/l/L/Z only) into polygon rings.
const polys = {};
for (const [cc, { path }] of Object.entries(map.paths)) {
  const rings = [];
  let ring = null;
  let x = 0;
  let y = 0;
  for (const [, c, args] of path.matchAll(/([MlLZ])([^MlLZ]*)/g)) {
    const n = args.split(/[ ,]+/).filter(Boolean).map(Number);
    if (c === "M") {
      x = n[0];
      y = n[1];
      ring = [[x, y]];
      rings.push(ring);
    } else if (c === "l") {
      for (let i = 0; i < n.length; i += 2) {
        x += n[i];
        y += n[i + 1];
        ring.push([x, y]);
      }
    } else if (c === "L") {
      for (let i = 0; i < n.length; i += 2) {
        x = n[i];
        y = n[i + 1];
        ring.push([x, y]);
      }
    }
  }
  polys[cc] = rings;
}

// Even-odd point-in-polygon across all of a country's rings.
const inside = (rings, px, py) => {
  let c = false;
  for (const r of rings)
    for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
      const [xi, yi] = r[i];
      const [xj, yj] = r[j];
      if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) c = !c;
    }
  return c;
};

// Hex grid: 6 px across, 5.2 px down, odd rows offset. Antarctica is dropped.
const DX = 6;
const DY = 5.2;
const H = 400;
const base = [];
const cc = {};
for (let row = 0, y = 3; y < H; row++, y = +(3 + row * DY).toFixed(1)) {
  for (let x = row % 2 ? 6 : 3; x < 900; x += DX) {
    for (const [k, rings] of Object.entries(polys)) {
      if (k !== "AQ" && inside(rings, x, y)) {
        const p = `M${x} ${y}h0`;
        base.push(p);
        cc[k] = cc[k] ?? [];
        cc[k].push(p);
        break;
      }
    }
  }
}

writeFileSync(
  resolve(root, "public/assets/map-base.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -3 906 ${H + 3}"><path fill="none" stroke="#262c28" stroke-width="3.3" stroke-linecap="round" d="${base.join("")}"/></svg>\n`,
);

const entries = Object.keys(cc)
  .sort()
  .map((k) => `  ${k}: "${cc[k].join("")}",`)
  .join("\n");
writeFileSync(
  resolve(root, "src/dashboard/render/map-data.ts"),
  `// GENERATED by scripts/gen-map.mjs — do not edit. Per-country dot paths for the
// hex dot map; the unlit base grid is public/assets/map-base.svg.

/** Height of the dot grid in map units (width is 900). */
export const MAP_H = ${H};

/** ISO 3166-1 alpha-2 code → SVG path of that country's dots. */
export const COUNTRY_DOTS: Record<string, string> = {
${entries}
};
`,
);
console.log(`gen-map: ${base.length} dots, ${Object.keys(cc).length} countries`);
